[package]
name = "macros"
version = "0.2.0-dev"
authors = ["rusty-snake"]
edition = "2018"
description = "Procedural Macros for firejail-profile"

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
