name: ShellCheck

on:
  push:
    paths:
      - 'make.sh'
  pull_request:
    paths:
      - 'make.sh'

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: shellchecl --version
    - run: shellcheck make.sh
