name: ShellCheck

on:
  push:
    paths:
      - .github/workflows/shellcheck.yml
      - 'make.sh'
  pull_request:
    paths:
      - .github/workflows/shellcheck.yml
      - 'make.sh'

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: shellcheck --version
    - run: shellcheck make.sh
